---
- name: Manage system groups
  group:
    name: '{{ item.name }}'
    gid: '{{ item.gid|default(omit) }}'
    system: '{{ item.system|default(omit) }}'
    state: '{{ "present" if item.disabled is undefined or not item.disabled|bool else "absent" }}'
  with_items: '{{ system_groups__list }}'
  when: (item.name is defined and item.name|trim and item.name != 'root')
